openapi: 3.0.0
info:
  title: GetMyServiceNowIncidents API
  description: API to retrieve and create ServiceNow incidents
  version: 1.0.0
servers:
  - url: https://dev270587.service-now.com/api
paths:
  /892928/declarative_agents/GetMyIncidents/{username}:
    get:
      operationId: getIncidents
      summary: Retrieve ServiceNow incidents
      description: Fetches a list of ServiceNow incidents
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string           
          description: The user's name to retrieve incidents. Please use the user name from the signed user.
      responses:
        '200':
          description: A list of incidents
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    number:
                      type: string
                      description: The number ID of the incident
                    short_description:
                      type: string
                      description: A brief description of the incident
                    state:
                      type: string
                      description: The current status of the incident

  /892928/declarative_agents/createincident:
    post:
      operationId: createIncident
      summary: Create a new incident
      description: Creates a new incident in ServiceNow on behalf of the logged in user. Return the number and the short description.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - short_description
                - description
                - username
              properties:
                short_description:
                  type: string
                  description: Brief description of the incident
                  example: "Can't read email"
                description:
                  type: string
                  description: Full description of the incident
                  example: "User can't access email on mail.company.com."
                username:
                  type: string
                  description: Username of who is creating the incident. Please use the user name from the signed user.
                  example: "jdoe"
                category:
                  type: string
                  description: Category of the incident
                  example: "network"
                impact:
                  type: integer
                  description: Impact level of the incident (1 = High, 2 = Medium, 3 = Low)
                  example: 3
                urgency:
                  type: integer
                  description: Urgency level of the incident (1 = High, 2 = Medium, 3 = Low)
                  example: 3
      responses:
        '201':
          description: Incident created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: "Incident created successfully"
                  sys_id:
                    type: string
                    description: Sys ID of the created incident
                    example: "b9a4f6131b45d0109eb3c243fe4bcb45"
                  number:
                    type: string
                    description: Incident number
                    example: "INC0010001"
        '400':
          description: Missing required fields (short_description or username)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Missing required fields: short_description or username"
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User not found with username: jdoe"
        '500':
          description: Error creating incident
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error creating incident: Record insert failed"

